# Generated by Django 2.2.7 on 2019-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
