# Generated by Django 2.2.7 on 2019-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='parties_involved',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parties Involved'),
        ),
    ]
