# Generated by Django 2.2.7 on 2019-11-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
