# Generated by Django 2.2.7 on 2019-11-08 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
    ]
