# Generated by Django 2.2.7 on 2019-11-08 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191108_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='date_issued',
        ),
        migrations.AddField(
            model_name='violation',
            name='datetime_issued',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.Driver')),
            ],
            options={
                'default_related_name': 'notifications',
            },
        ),
    ]
