# Generated by Django 2.2.7 on 2019-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_violation_is_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('S', 'Status'), ('V', 'Violation')], max_length=1, verbose_name='Notification Type'),
        ),
    ]
