# Generated by Django 2.2.7 on 2019-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191107_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile-picture/', verbose_name='Profile Picture'),
        ),
    ]
