# Generated by Django 2.2.7 on 2019-11-08 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191109_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='datetime_issued',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime Issued'),
        ),
    ]
