# Generated by Django 2.2.7 on 2019-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191107_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile-pictures/', verbose_name='Profile Picture'),
        ),
    ]
