# Generated by Django 2.2.7 on 2019-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191109_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='datetime_issued',
            field=models.DateTimeField(verbose_name='Datetime Issued'),
        ),
    ]
