# Generated by Django 2.2.7 on 2019-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191107_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Short Description'),
        ),
    ]
