# Generated by Django 2.2.7 on 2019-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fee_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.CharField(max_length=15, verbose_name='License Number'),
        ),
    ]
